name: Build macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    name: Build macOS (ARM64 Native)
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # Update brew and install dependencies for native arm64
          brew update
          # Remove any conflicting cmake installations
          brew uninstall --ignore-dependencies cmake || true
          brew install cmake libpng

      - name: Configure CMake
        run: |
          mkdir -p build-macos
          cd build-macos
          echo "🔧 Configuring ARM64 native build"
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0
    
      - name: Build
        run: |
          cd build-macos
          echo "🔨 Building ARM64 native binary"
          cmake --build . --config Release -j$(sysctl -n hw.ncpu) --parallel
    
      - name: Create App Bundle and DMG
        run: |
          cd build-macos
          mkdir -p PixelShaper.app/Contents/MacOS
          mkdir -p PixelShaper.app/Contents/Resources
          cp build/PixerShaper PixelShaper.app/Contents/MacOS/
          cp -r build/assets PixelShaper.app/Contents/Resources/
          
          # Create Info.plist
          cat > PixelShaper.app/Contents/Info.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleExecutable</key>
              <string>PixerShaper</string>
              <key>CFBundleIdentifier</key>
              <string>com.dcubix.pixelshaper</string>
              <key>CFBundleName</key>
              <string>PixelShaper</string>
              <key>CFBundleDisplayName</key>
              <string>PixelShaper</string>
              <key>CFBundleVersion</key>
              <string>1.0.0</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0.0</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>NSHighResolutionCapable</key>
              <true/>
              <key>LSMinimumSystemVersion</key>
              <string>10.15</string>
          </dict>
          </plist>
          EOF
          
          # Create DMG
          mkdir -p dmg-temp
          cp -r PixelShaper.app dmg-temp/
          ln -s /Applications dmg-temp/Applications
          
          DMG_NAME="PixelShaper-macOS-ARM64.dmg"
          hdiutil create -volname "PixelShaper" -srcfolder dmg-temp -ov -format UDZO "$DMG_NAME"
          echo "📦 Created DMG: $DMG_NAME"
    
      - name: Upload macOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pixelshaper-macos-arm64
          path: |
            build-macos/build/PixerShaper
            build-macos/build/assets/
            build-macos/PixelShaper.app/
            build-macos/PixelShaper-macOS-ARM64.dmg
